name: Fetch and Update Data

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        run: |
          git clone https://github.com/${{ github.repository }} .

      - name: Set up Python
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip

      - name: Install dependencies
        run: pip3 install requests

      - name: Run Fetch Script
        env:
          DATA_URL: ${{ secrets.DATA_URL }}
        run: python3 fetch_data.py

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add vpn-Ha.txt
          git diff --cached --exit-code || git commit -m "Update vpn-Ha.txt"
          git push
