name: Fetch and Update Data

on:
  schedule:
    - cron: '*/59 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Create Python script
        run: |
          echo "import requests" > fetch_data.py
          echo "import os" >> fetch_data.py
          echo "url = os.getenv('DATA_URL')" >> fetch_data.py
          echo "response = requests.get(url)" >> fetch_data.py
          echo "if response.status_code == 200:" >> fetch_data.py
          echo "    with open('vpn.txt', 'w') as file:" >> fetch_data.py
          echo "        file.write(response.text)" >> fetch_data.py
          echo "else:" >> fetch_data.py
          echo "    print(f'Failed to fetch data. Status code: {response.status_code}')" >> fetch_data.py

      - name: Fetch and Save Data
        env:
          DATA_URL: ${{ secrets.DATA_URL }}
        run: python fetch_data.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add vpn.txt
          git commit -m "Update vpn.txt"
          git push
