name: Fetch and Update Data

on:
  schedule:
    - cron: '*/59 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Fetch and Save Data
      env:
        DATA_URL: ${{ secrets.DATA_URL }}
      run: |
        python -c "
import requests
import os

url = os.getenv('DATA_URL')
response = requests.get(url)
if response.status_code == 200:
    with open('vpn.txt', 'w') as file:
        file.write(response.text)
else:
    print(f'Failed to fetch data. Status code: {response.status_code}')
        "

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add mixed_data.txt
        git commit -m "Update vpn.txt"
        git push
